name: disaster-api

channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10
  - pip
  - numpy=1.24.3
  - pandas=2.1.3
  - scikit-learn=1.3.2
  - xgboost=2.0.3
  - prophet=1.1.5
  - openpyxl=3.1.2
  - matplotlib=3.7.3
  - plotly=5.18.0

  # ✅ Deep Learning & CV
  # Actually Model is traind on this version
  # tensorflow=2.19.0
  # Required for Keras/MobileNetV2
  # pillow==10.1.0
  # as used in the notebooks/environment.yml
  # Due to compatibility issues, we are not including TensorFlow and Pillow in this requirements.txt.
  # we are using ONNX Converted model for inference in the API.

  # ONNX Core
  - onnx=1.15.0
  - onnxruntime=1.17.0

  # Linux build tools (ignored on Windows/Mac)
  # - gcc_linux-64
  # - gxx_linux-64
  # - make

  # Pip dependencies
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.1.2
      - torchvision==0.16.2
      - torchaudio==2.1.2
      - fastapi==0.104.1
      - uvicorn[standard]==0.24.0
      - transformers[torch]==4.35.2
      - accelerate==0.25.0
      - joblib==1.3.2
      - python-multipart==0.0.6
      - pydantic==2.4.2
      - python-dotenv==1.0.1

      # NEW PACKAGES ADDED
      - google-generativeai
      - chromadb
      - pypdf
      - tiktoken
      - sentence-transformers

# IMPORTANT (MUST): # Ensure Microsoft Visual C++ Redistributable (X64 and x86 both) are installed.