name: ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # or your specific Python version
  - pip
  - pandas=2.2.3
  - numpy=1.26.4
  - scikit-learn=1.3.2
  - xgboost=3.0.2
  - joblib=1.5.0
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - pip:
      - torch==2.5.1
      - transformers==4.36.2
      - datasets==3.6.0
      - tqdm==4.67.1
      - prophet==1.1.7
