name: streamlit_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # or the version you're using
  - pip
  - pip:
      - numpy==1.26.4
      - pandas==2.3.1
      - plotly==6.2.0
      - requests==2.32.4
      - streamlit==1.47.0
